import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import { Button } from 'components';
import { signIn, useSession } from 'next-auth/react';
import { useRouter } from 'next/router';

const Home: NextPage = () => {
  const router = useRouter();
  const { data: session } = useSession();

  const handleLogin = () => signIn('keycloak', { callbackUrl: '/todos' });

  React.useEffect(() => {
    if(session) router.push('/todos');
  }, [session]);

  return (
    <div className='app'>
      <Head>
        <title>ToDos App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button
        variant='contained'
        onClick={handleLogin}>
        Login
      </Button>
    </div>
  )
}

export default Home
