import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import { TextField } from '@mui/material';

const Home: NextPage = () => {
  return (
    <div className='app'>
      <Head>
        <title>ToDos App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TextField
        label='Test'
        variant='outlined'
      />
    </div>
  )
}

export default Home
